# Generated by Django 6.1 on 2026-08-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_type', models.CharField(choices=[('DOMAIN', 'Domain'), ('HOSTING', 'Hosting'), ('EMAIL', 'Email'), ('OTHER', 'Other')], max_length=10)),
                ('fields_enc', models.BinaryField()),
                ('hmac_tag', models.CharField(max_length=64)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_created', to='accounts.user')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_reviewed', to='accounts.user')),
            ],
            options={
                'db_table': 'vault_credential_record',
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_fields_enc', models.BinaryField()),
                ('proposed_hmac', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests_reviewed', to='accounts.user')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_submitted', to='accounts.user')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='vault.credentialrecord')),
            ],
            options={
                'db_table': 'vault_change_request',
            },
        ),
        migrations.CreateModel(
            name='KeyRotationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('USER', 'User'), ('PROJECT', 'Project')], max_length=10)),
                ('scope_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('SCHEDULED', 'Scheduled rotation'), ('REVOCATION', 'Access revocation'), ('MANUAL', 'Manual trigger')], max_length=12)),
                ('previous_key_fingerprint', models.CharField(max_length=64)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_triggered', to='accounts.user')),
            ],
            options={
                'db_table': 'vault_key_rotation_log',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_enc', models.BinaryField()),
                ('name_hmac', models.CharField(max_length=64)),
                ('rsa_pub_n', models.TextField()),
                ('rsa_pub_e', models.BigIntegerField(default=65537)),
                ('rsa_priv_wrapped', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to='accounts.user')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='accounts.user')),
            ],
            options={
                'db_table': 'vault_project',
            },
        ),
        migrations.CreateModel(
            name='FeedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROJECT_CREATED', 'Project created'), ('MEMBER_ADDED', 'Member added'), ('MEMBER_REVOKED', 'Member revoked'), ('RECORD_REQUESTED', 'Record requested'), ('RECORD_APPROVED', 'Record approved'), ('RECORD_REJECTED', 'Record rejected'), ('RECORD_EDITED', 'Record edited'), ('CHANGE_REQUESTED', 'Change requested'), ('CHANGE_APPROVED', 'Change approved'), ('CHANGE_REJECTED', 'Change rejected'), ('ISSUE_REPORTED', 'Issue reported'), ('ISSUE_RESOLVED', 'Issue resolved'), ('NOTE_ADDED', 'Note added'), ('KEY_ROTATED', 'Key rotated')], max_length=20)),
                ('message_enc', models.BinaryField()),
                ('message_hmac', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_events', to='accounts.user')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_events', to='vault.credentialrecord')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_events', to='vault.project')),
            ],
            options={
                'db_table': 'vault_feed_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='vault.project'),
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapped_project_privkey', models.BinaryField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants_issued', to='accounts.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='accounts.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='vault.project')),
            ],
            options={
                'db_table': 'vault_access_grant',
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('project', 'user'), name='unique_active_grant_per_project_user')],
            },
        ),
    ]
