# Generated by Django 6.1 on 2026-09-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialrecord',
            name='environment',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('STAGING', 'Staging'), ('DEVELOPMENT', 'Development')], default='PRODUCTION', max_length=12),
        ),
        migrations.AddField(
            model_name='credentialrecord',
            name='expires_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
