# Generated by Django 6.1 on 2026-09-04 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_failed_login_attempts_user_locked_until'),
        ('vault', '0002_credentialrecord_environment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialrecord',
            name='password_last_rotated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RecordAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('REVEAL', 'Revealed'), ('COPY', 'Copied')], max_length=10)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='vault.credentialrecord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_access_logs', to='accounts.user')),
            ],
            options={
                'db_table': 'vault_record_access_log',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
