# Generated by Django 6.1 on 2026-08-28 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_lookup', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email_lookup', models.CharField(db_index=True, max_length=64, unique=True)),
                ('username_enc', models.BinaryField()),
                ('email_enc', models.BinaryField()),
                ('contact_enc', models.BinaryField(blank=True, default=b'')),
                ('profile_hmac', models.CharField(max_length=64)),
                ('password_hash', models.BinaryField()),
                ('password_salt', models.BinaryField()),
                ('rsa_pub_n', models.TextField()),
                ('rsa_pub_e', models.BigIntegerField(default=65537)),
                ('rsa_priv_wrapped', models.BinaryField()),
                ('ecc_pub_x', models.TextField()),
                ('ecc_pub_y', models.TextField()),
                ('ecc_priv_wrapped', models.BinaryField()),
                ('totp_secret_wrapped', models.BinaryField()),
                ('totp_confirmed', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('PROJECT_MANAGER', 'Project Manager'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('BACKEND_DEVELOPER', 'Backend Developer')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts_user',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hmac', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_fingerprint', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.user')),
            ],
            options={
                'db_table': 'accounts_session',
            },
        ),
        migrations.CreateModel(
            name='PendingLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_hmac', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_fingerprint', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_logins', to='accounts.user')),
            ],
            options={
                'db_table': 'accounts_pending_login',
            },
        ),
    ]
